backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "projetos"
    label: "Projetos"
    folder: "content/projects"
    create: true
    editor:
     preview: true
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Data", name: "date", widget: "datetime" }
      - { label: "Imagens", name: "images", widget: "image" }
      - { label: "Descrição", name: "description", widget: "markdown" }

  - name: "pages"
    label: "Pages"
    files:
      - label: "Sobre"
        name: "sobre"
        file: "site/content/about.yml"
        fields:
          - { label: "Título", name: title, widget: string }
          - { label: "Foto", name: "picture", widget: "image", allow_multiple: false }
          - { label: "Text", name: "text", widget: "markdown" }